name: Publish to web branch
on:
  push:
    branches:
     - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./
    steps:
      - uses: actions/checkout@v2
      - name: Setup Emscripten toolchain
        uses: mymindstorm/setup-emsdk@v11
      - name: Make with `emmake make`
        run: emmake make
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: www
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
